Remove reentry scan again and disable other workflows

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -28,7 +28,6 @@ jobs:
     - name: Install python dependencies
       run: |
         pip install -e .[docs]
-        reentry scan
 
     - name: Build documentation
       env:
@@ -36,99 +35,99 @@ jobs:
       run: |
         SPHINXOPTS='-nW' make -C docs html
 
-  pre-commit:
+#   pre-commit:
 
-    runs-on: ubuntu-18.04
-    timeout-minutes: 30
+#     runs-on: ubuntu-18.04
+#     timeout-minutes: 30
 
-    steps:
-    - uses: actions/checkout@v2
+#     steps:
+#     - uses: actions/checkout@v2
 
-    - name: Cache python dependencies
-      id: cache-pip
-      uses: actions/cache@v1
-      with:
-        path: ~/.cache/pip
-        key: pip-pre-commit-${{ hashFiles('**/setup.json') }}
-        restore-keys: |
-          pip-pre-commit-
+#     - name: Cache python dependencies
+#       id: cache-pip
+#       uses: actions/cache@v1
+#       with:
+#         path: ~/.cache/pip
+#         key: pip-pre-commit-${{ hashFiles('**/setup.json') }}
+#         restore-keys: |
+#           pip-pre-commit-
 
-    - name: Set up Python 3.7
-      uses: actions/setup-python@v2
-      with:
-        python-version: 3.7
+#     - name: Set up Python 3.7
+#       uses: actions/setup-python@v2
+#       with:
+#         python-version: 3.7
 
-    - name: Install python dependencies
-      run: |
-        pip install .[pre-commit,testing]
-        pip freeze
+#     - name: Install python dependencies
+#       run: |
+#         pip install .[pre-commit,testing]
+#         pip freeze
 
-    - name: Run pre-commit
-      run: |
-        pre-commit run --all-files || (git status --short; git diff ; exit 1)
+#     - name: Run pre-commit
+#       run: |
+#         pre-commit run --all-files || (git status --short; git diff ; exit 1)
 
-  tests:
+#   tests:
 
-    runs-on: ubuntu-18.04
-    timeout-minutes: 30
+#     runs-on: ubuntu-18.04
+#     timeout-minutes: 30
 
-    strategy:
-      matrix:
-        python-version: [3.6, 3.7, 3.8, 3.9]
+#     strategy:
+#       matrix:
+#         python-version: [3.6, 3.7, 3.8, 3.9]
 
-    services:
-      postgres:
-        image: postgres:10
-        env:
-          POSTGRES_DB: test_${{ matrix.backend }}
-          POSTGRES_PASSWORD: ''
-          POSTGRES_HOST_AUTH_METHOD: trust
-        ports:
-        - 5432:5432
-      rabbitmq:
-        image: rabbitmq:latest
-        ports:
-        - 5672:5672
+#     services:
+#       postgres:
+#         image: postgres:10
+#         env:
+#           POSTGRES_DB: test_${{ matrix.backend }}
+#           POSTGRES_PASSWORD: ''
+#           POSTGRES_HOST_AUTH_METHOD: trust
+#         ports:
+#         - 5432:5432
+#       rabbitmq:
+#         image: rabbitmq:latest
+#         ports:
+#         - 5672:5672
 
-    steps:
-    - uses: actions/checkout@v2
+#     steps:
+#     - uses: actions/checkout@v2
 
-    - name: Cache python dependencies
-      id: cache-pip
-      uses: actions/cache@v1
-      with:
-        path: ~/.cache/pip
-        key: pip-${{ matrix.python-version }}-tests-${{ hashFiles('**/setup.json') }}
-        restore-keys: |
-          pip-${{ matrix.python-version }}-tests
+#     - name: Cache python dependencies
+#       id: cache-pip
+#       uses: actions/cache@v1
+#       with:
+#         path: ~/.cache/pip
+#         key: pip-${{ matrix.python-version }}-tests-${{ hashFiles('**/setup.json') }}
+#         restore-keys: |
+#           pip-${{ matrix.python-version }}-tests
 
-    - name: Set up Python ${{ matrix.python-version }}
-      uses: actions/setup-python@v2
-      with:
-        python-version: ${{ matrix.python-version }}
+#     - name: Set up Python ${{ matrix.python-version }}
+#       uses: actions/setup-python@v2
+#       with:
+#         python-version: ${{ matrix.python-version }}
 
-    - name: Install system dependencies
-      run: |
-        sudo apt update
-        sudo apt install postgresql-10
+#     - name: Install system dependencies
+#       run: |
+#         sudo apt update
+#         sudo apt install postgresql-10
 
-    - name: Install python dependencies
-      run: |
-        pip install --upgrade wheel setuptools
-        pip install git+https://github.com/aiidateam/aiida-testing.git@export_cache
-        pip install .[testing]
-        reentry scan
+#     - name: Install python dependencies
+#       run: |
+#         pip install --upgrade wheel setuptools
+#         pip install git+https://github.com/aiidateam/aiida-testing.git@export_cache
+#         pip install .[testing]
+#         reentry scan
 
-    - name: Run pytest
-      run: |
-       # create fake codes for tests to work on ci
-       cd ./tests/
-       touch local_exe/inpgen && chmod +x local_exe/inpgen
-       touch local_exe/fleur && chmod +x local_exe/fleur
-       ./run_all_cov.sh
+#     - name: Run pytest
+#       run: |
+#        # create fake codes for tests to work on ci
+#        cd ./tests/
+#        touch local_exe/inpgen && chmod +x local_exe/inpgen
+#        touch local_exe/fleur && chmod +x local_exe/fleur
+#        ./run_all_cov.sh
 
-    - name: Upload report to Codecov
-      uses: codecov/codecov-action@v1
-      with:
-        file: ./tests/coverage.xml
-        fail_ci_if_error: False
+#     - name: Upload report to Codecov
+#       uses: codecov/codecov-action@v1
+#       with:
+#         file: ./tests/coverage.xml
+#         fail_ci_if_error: False
